CREATE TABLE USUARIOS(
   ID_USUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   USUARIO VARCHAR(30) NOT NULL,
   SENHA VARCHAR(30) NOT NULL,
   NOME VARCHAR(100) NOT NULL,
   EMAIL VARCHAR(50) NOT NULL,
   ATIVO BIT NOT NULL
);

INSERT INTO USUARIOS(USUARIO, SENHA, NOME, EMAIL, ATIVO) VALUES ('herculeskarkow', 'hercules123', 'Hercules Affonso Karkow', 'heco.karkow@gmail.com', 1);

SELECT * FROM USUARIOS;